blank_issues_enabled: false
contact_links:
  - name: Contributing guidelines
    url: https://github.com/Antiz96/arch-update/blob/main/CONTRIBUTING.md
    about: Please, read the contributing guidelines before opening an issue
