name: Test suite
on: pull_request

env:
  REPO_NAME: ${{ github.event.repository.name }}

jobs:
  test_suite:
    runs-on: ubuntu-latest

    container:
      image: docker.io/library/alpine:latest
      options: --privileged

    steps:
      - name: Update container
        run: apk update && apk upgrade

      - name: Install packages
        run: apk add git shellcheck py3-pip && pip install codespell

      - name: Clone repo
        run: git clone $GITHUB_SERVER_URL/$GITHUB_REPOSITORY && cd $REPO_NAME && git checkout $GITHUB_HEAD_REF

      - name: Run shellcheck
        run: find . -name '*.sh' -exec shellcheck --color=always {} +

      - name: Run codespell
        run: codespell
